name: Publish Documentation to Github Pages 📘
on:
  push:
    branches:
      - main
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.x
      - name: Setup Yarn
        uses: actions/cache@v3.3.3
        with:
          path: node_modules
          key: yarn-cache-${{ hashFiles('**/yarn.lock', '.yarnrc') }}
          restore-keys: yarn-cache-
      - run: yarn install --immutable
      - name: Build docs
        run: yarn build:docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          commit_message: "docs: update"
          force_orphan: true
